import enum


class Campus(enum.Enum):
    east_campus = 'ctl00$ContentPlaceHolder1$cb_East'
    west_campus = 'ctl00$ContentPlaceHolder1$cb_West'
    off_campus = 'ctl00$ContentPlaceHolder1$cb_OffCamp'


class Environment(enum.Enum):
    online = 'ctl00$ContentPlaceHolder1$cb_Onl'
    hybrid = 'ctl00$ContentPlaceHolder1$cb_Hyb'


class MeetDays(enum.Enum):
    sunday = 'ctl00$ContentPlaceHolder1$cb_Sun'
    monday = 'ctl00$ContentPlaceHolder1$cb_Mon'
    tuesday = 'ctl00$ContentPlaceHolder1$cb_Tue'
    wednesday = 'ctl00$ContentPlaceHolder1$cb_Wed'
    thursday = 'ctl00$ContentPlaceHolder1$cb_Thu'
    friday = 'ctl00$ContentPlaceHolder1$cb_Fri'
    saturday = 'ctl00$ContentPlaceHolder1$cb_Sat'


class ShortTerm(enum.Enum):
    first_half = 'ctl00$ContentPlaceHolder1$cb_ShortTerm01'
    second_half = 'ctl00$ContentPlaceHolder1$cb_ShortTerm02'


class ClassStatus(enum.Enum):
    open = 'ctl00$ContentPlaceHolder1$cb_Open'
    closed = 'ctl00$ContentPlaceHolder1$cb_Closed'


class Term(enum.Enum):
    spring_2021 = '2021MSP'


class Subject(enum.Enum):
    All = 'All'
    MADJU = 'MADJU'
    MAG = 'MAG'
    MAGEC = 'MAGEC'
    MAGGE = 'MAGGE'
    MAGM = 'MAGM'
    MANAT = 'MANAT'
    MANSC = 'MANSC'
    MANTHR = 'MANTHR'
    MAP = 'MAP'
    MART = 'MART'
    MASTRO = 'MASTRO'
    MAUBDY = 'MAUBDY'
    MAUTEC = 'MAUTEC'
    MBIO = 'MBIO'
    MBOT = 'MBOT'
    MBUSAD = 'MBUSAD'
    MCHEM = 'MCHEM'
    MCLDDV = 'MCLDDV'
    MCMPET = 'MCMPET'
    MCMPGR = 'MCMPGR'
    MCMPSC = 'MCMPSC'
    MCOLSK = 'MCOLSK'
    MCOMM = 'MCOMM'
    MCSCI = 'MCSCI'
    MDANCE = 'MDANCE'
    MEASCI = 'MEASCI'
    MECON = 'MECON'
    MEHS = 'MEHS'
    MELIC = 'MELIC'
    MELTEC = 'MELTEC'
    MELW = 'MELW'
    MEMS = 'MEMS'
    MENGL = 'MENGL'
    MENGR = 'MENGR'
    MENSCI = 'MENSCI'
    METHS = 'METHS'
    MFAMLF = 'MFAMLF'
    MFDNTR = 'MFDNTR'
    MFREN = 'MFREN'
    MFTECH = 'MFTECH'
    MGEOG = 'MGEOG'
    MGEOL = 'MGEOL'
    MGERM = 'MGERM'
    MGERON = 'MGERON'
    MGUIDE = 'MGUIDE'
    MHE = 'MHE'
    MHIST = 'MHIST'
    MHUMAN = 'MHUMAN'
    MHUMSR = 'MHUMSR'
    MIIS = 'MIIS'
    MITAL = 'MITAL'
    MKIN = 'MKIN'
    MLIBR = 'MLIBR'
    MLOGST = 'MLOGST'
    MMACH = 'MMACH'
    MMATH = 'MMATH'
    MMDAST = 'MMDAST'
    MMETEO = 'MMETEO'
    MMICRO = 'MMICRO'
    MMUSA = 'MMUSA'
    MMUSC = 'MMUSC'
    MMUSE = 'MMUSE'
    MMUSG = 'MMUSG'
    MMUSP = 'MMUSP'
    MMUST = 'MMUST'
    MNR = 'MNR'
    MNURSE = 'MNURSE'
    MNURSK = 'MNURSK'
    MNURWE = 'MNURWE'
    MOFADM = 'MOFADM'
    MPE = 'MPE'
    MPEA = 'MPEA'
    MPEC = 'MPEC'
    MPEM = 'MPEM'
    MPEVM = 'MPEVM'
    MPEVW = 'MPEVW'
    MPEW = 'MPEW'
    MPHILO = 'MPHILO'
    MPHSCI = 'MPHSCI'
    MPHYS = 'MPHYS'
    MPHYSO = 'MPHYSO'
    MPLSC = 'MPLSC'
    MPOLSC = 'MPOLSC'
    MPSYCH = 'MPSYCH'
    MREAD = 'MREAD'
    MREC = 'MREC'
    MRLES = 'MRLES'
    MRSCR = 'MRSCR'
    MSIGN = 'MSIGN'
    MSM = 'MSM'
    MSOCIO = 'MSOCIO'
    MSOCSC = 'MSOCSC'
    MSPAN = 'MSPAN'
    MSPCOM = 'MSPCOM'
    MSPELL = 'MSPELL'
    MSTSK = 'MSTSK'
    MTHETR = 'MTHETR'
    MTUTOR = 'MTUTOR'
    MWELD = 'MWELD'
    MWKFSK = 'MWKFSK'
    MZOOL = 'MZOOL'
